version: '2'
services:
  mypress:
    build: mypress/.
    environment:
      - NODE_ENV=production
      - PORT=8080
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./mypress:/usr/src/app
    command: bash -c "npm install pg && npm install && npm start"
    expose:
      - '8080'
    ports:
      - '8080:8080'
    links:
      - mypress-postgres:postgres
      - mypress-redis:redis
  mypress-postgres:
    build: postgres/.
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=mypress
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    expose:
      - '5432'
  mypress-redis:
    build: redis/.
    expose:
      - '6379'
